spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://localhost:3306/test

  jpa:
    database: mysql
    hibernate:
      # ddl-auto를 한번도 안쓸수도 있다. (실무에서는 잘 안쓴다)
      # 단, 그 경우 Entity 클래스의 정의와 완벽히 일치하는 Table이
      # 사용하고자 하는 데이터베이스에 잘 만들어져 있어야 한다.
      ddl-auto: create
    show-sql: false